config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  devise_for :users,controllers:{sessions:"users/sessions",confirmations:"users/confirmations",passwords:"users/passwords",registrations:"users/registrations" }, path: "auth",
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :home

  resources :users
  resources :roles
  resources :menus
  resources :log_files
  resources :sys_params
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_and_belongs_to_many :menus, :join_table => :roles_menus
  has_and_belongs_to_many :roles, :join_table => :roles_menus
  belongs_to :parent, :class_name => 'Menu', foreign_key: 'parent_id', primary_key: 'id'

  delegate :name, to: :parent, prefix: true, allow_nil: true

  enum resource_type: { one: 1, two: 2 }
  enum resource_type: { one_level: '1', two_level: '2' }
  enum status: { active: 1, archived: 0 }


  class << self
    def find_by_user(user_id, level, parent_id)
      user = User.find(user_id)
      roles = user.roles
      menus = []
      roles.each do |role|
        if level == Menu.resource_types[:one]
          role_menus = role.menus.where(resource_type: level, status: Menu.active)
        else
          role_menus = role.menus.where(resource_type: level, parent_id: parent_id, status: Menu.active)
        end
        role_menus.each do |menu|
          menus << menu
        end
      end
      p menus
      menus.uniq
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  load_and_authorize_resource except: [:create]

  def index
    params[:q] ||= ActionController::Parameters.new
    params[:q][:status_eq] = Menu.statuses[:active]
    @q = Menu.ransack(params[:q])
    @menus = @q.result.page(@page).per(@page_size)
    @menus.total_count
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      flash[:notice] = "保存成功"
      redirect_to :menus
    else
      flash[:notice] = "保存失败"
      render :new
    end
  end

  def update
    if @menu.update(menu_params)
      flash[:notice] = "更新成功"
      redirect_to :menus
    else
      flash[:notice] = "更新失败"
      render :edit
    end
  end

  def destroy
    if @menu.update(status: Menu.statuses[:archived])
      flash[:notice] = "删除成功"
    else
      flash[:notice] = "删除失败"
    end
    redirect_to :menus
  end

  def new
    @menu.resource_type = Menu.resource_types[:two_level]
  end

  private

  def menu_params
    params.require(:menu).permit(:id, :name, :desc, :source, :parent_id, :created_at, :updated_at, :status, :resource_type)
  end
end

app/helpers/menus_helper.rb
module MenusHelper
  def parents_menus
    Menu.where( resource_type: Menu.resource_types[:one], status: Menu.statuses[:active] )
  end
end

app/views/menus/_form.html.erb
<%= bootstrap_form_for(@menu, layout: :horizontal, :html => { class: 'pjax-form col-sm-10' }) do |f| %>
    <%= f.select :resource_type, [['一级菜单',1],['二级菜单',2]], selected: 2 , label: "菜单等级"  %>
    <div id="parant">
      <%= f.collection_select(:parent_id, parents_menus, :id, :name, label: "上级") %>
    </div>
    <%= f.text_field :name, label: "名称" %>
    <%= f.text_field :source, label: "地址" %>
    <%= f.text_field :desc, label: "备注" %>
    <div class="form-group text-center">
      <%= link_to '取消', menus_path, :class => 'btn btn-default' %>
      <%= f.submit "保存", class: "btn meedesidy_btn_save" %>
    </div>
<% end %>
<script>
  $(function () {
    $("#menu_resource_type").change(function(){
      if($(this).val() == "1"){
        $('#parant').hide();
        $("#menu_source").attr("disabled",true);
      }else{
        $('#parant').show();
        $("#menu_source").attr("disabled",false);
      }
    })
  })
</script>

app/views/menus/edit.html.erb
<%= render 'shared/crumbs', menu: '系统管理', title: "菜单信息", name: '编辑菜单' %>
<%= render 'menus/form' %>

app/views/menus/index.html.erb
<%= render 'shared/crumbs', menu: '系统管理' ,title: "菜单信息", name: '菜单信息' %>
<div class="cl-mcont">
  <div class="head">
    <h3>查询</h3><hr/>
    <%= search_form_for @q, :html => {:class => 'pjax-form'} do |f| %>
        <div class="form-group col-md-4">
          <%= f.label "名称：", class: "control-label col-md-3" %>
          <div class="col-md-9">
            <%= f.search_field :name_cont, class: 'form-control' %>
          </div>
        </div>
        <%= link_to '新增', :new_menu, class: "btn btn-info"%>
        <button type="submit" class="btn btn-success" data-toggle="modal" data-target="#search_model">查询</button>
    <% end %>
  </div>
</div>
<div class="cl-mcont">
  <div class="content">
    <div class="table-responsive">
      <table class="table no-border hover">
        <thead class="no-border">
        <tr>
          <th><strong>名称</strong></th>
          <th><strong>级别</strong></th>
          <th><strong>父级</strong></th>
          <th><strong>地址</strong></th>
          <th style="width:15%;" class="text-center"><strong>操作</strong></th>
        </tr>
        </thead>
        <tbody class="no-border-y">
        <% @menus.each_with_index do |menu, index|%>
          <tr>
            <td><%= menu.name %></td>
            <td><%= menu.resource_type_i18n %></td>
            <td><%= menu.parent_name %></td>
            <td><%= menu.source %></td>
            <td class="text-center"><%= link_to  content_tag(:i, '', class: "fa fa-pencil"), edit_menu_path(menu), class: "label label-default" %>
              <%= link_to content_tag(:i, '', class: "fa fa-times"), menu_path(menu), class: "label label-danger", method: :delete, data: { confirm: "是否删除#{menu.name}?" } %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/menus/new.html.erb
<%= render 'shared/crumbs', menu: '系统管理', title: "菜单信息", name: '新建菜单' %>
<%= render 'menus/form' %>