config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  devise_for :users,controllers:{sessions:"users/sessions",confirmations:"users/confirmations",passwords:"users/passwords",registrations:"users/registrations" }, path: "auth",
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :home

  resources :users
  resources :roles
  resources :menus
  resources :log_files
  resources :sys_params
end

app/models/log_file.rb
class LogFile < ApplicationRecord
  has_many :log_errors

  def file_name
    File.join(address, name)
  end
end

app/controllers/log_files_controller.rb
class LogFilesController < ApplicationController
  load_and_authorize_resource except: [:create]

  def index
    address = SysParam.find_by_code(:log_address).val
    projects = SysParam.find_by_code(:project).val.split(',')
    p projects
    projects.each do |item|
      path = File.join(address, item)
      return redirect_to :log_files unless File::directory?(path)
      Dir.entries(path).each do |f|
        file_name = File.join(path, f)
        break if File::directory? file_name
        log_date = f.split('-')[1]
        LogFile.new({name: f, log_date: log_date, address: path, project_name: item}).save if LogFile.find_by(name: f, project_name: item).blank?
      end
    end


    @q = LogFile.ransack(params[:q])
    @log_files = @q.result
  end

  def new
    address = SysParam.find_by_code(:log_address).val
    projects = SysParam.find_by_code(:project).val.split(',')
    projects.each do |item|
      path = File.join(address, item)
      return redirect_to :log_files unless File::directory?(path)
      Dir.entries(path).each do |f|
        file_name = File.join(path, f)
        break if File::directory? file_name
        p read_file file_name if File.file? file_name

      end
    end
  end

  def edit
    if @log_file.log_errors.blank?
      @error_logs = read_file(@log_file)
    end
    @error_logs = @log_file.log_errors
  end

  private

  def read_file log_file
    file_name = log_file.file_name
    @list = Redis::List.new('list_name', :maxlength => 25)
    error_lines = []
    error_line_num = 0
    File.open(file_name).each_line do |line|
      @list << line
      error_line_num = 15 if error_line? line
      if error_line_num.zero?
        temp_lines = ""
        @list.each do |el|
          temp_lines << el
        end
        log_error = LogError.build_from_error temp_lines, log_file.id if log_file.log_errors.blank?
        error_lines << temp_lines
      end
      error_line_num -= 1 if error_line_num >= 0
    end
    error_lines
  end

  def read_files file_name
    error_lines = []
    error_line_num = 0
    @list = Redis::List.new('list_name', :maxlength => 25)
    File.open(file_name).each_line do |line|
      @list << line
      if error_line? line
        error_line_num = 15
      end
      if error_line_num.zero?
        @list.each do |el|
          error_lines << el
        end
      end
      error_line_num -= 1 if error_line_num >= 0
    end
    error_lines
  end

  def error_line?(line)
    (line =~ / Server Error/).present? ||
        (line =~ /ActionView::Template::Error/).present? ||
        (line =~ /Mysql2::Error/).present? ||
        (line =~ /undefined method/)
  end
end

app/helpers/log_files_helper.rb
module LogFilesHelper
end

app/views/log_files/edit.html.erb
<%= render 'shared/crumbs', menu: '日志管理', title: "日志获取", name: '查看异常' %>


<div class="cl-mcont">
  <ul class="cbp_tmtimeline">
    <% @error_logs.each do |log| %>
    <li>
      <time class="cbp_tmtime" datetime="2013-04-10 18:30">
        <span><%= log.error_date %></span> <span><%= log.error_time[0,8] %></span></time>
      <div class="cbp_tmicon cbp_tmicon-phone"></div>
      <div class="cbp_tmlabel">
        <h2><%= log.name %></h2>
        <pre><%= log.content %></pre>
      </div>
    </li>
    <% end %>
  </ul>
</div>
<style>
  pre{
    white-space:pre-wrap;
    white-space:-moz-pre-wrap;
    white-space:-pre-wrap;
    white-space:-o-pre-wrap;
    word-wrap:break-word;
    background-color: #4E9DFF;
  }
</style>

app/views/log_files/index.html.erb
<%= render 'shared/crumbs', menu: '日志管理' ,title: "日志获取" %>


<div class="cl-mcont">
  <div class="head">
    <h3>查询</h3><hr/>
    <%= search_form_for @q, :html => {:class => 'pjax-form'} do |f| %>
        <div class="form-group col-md-4">
          <%= f.label "名称：", class: "control-label col-md-3" %>
          <div class="col-md-9">
            <%= f.search_field :name_cont, class: 'form-control' %>
          </div>
        </div>
        <%= link_to '新增', :new_role, class: "btn btn-info"%>
        <button type="submit" class="btn btn-success" data-toggle="modal" data-target="#search_model">查询</button>
        <%= link_to '初始化', :new_log_file, class: "btn btn-warning btn-rad" %>
    <% end %>
  </div>
</div>
<div class="cl-mcont">
  <div class="content">
    <div class="table-responsive">
      <table class="table no-border hover">
        <thead class="no-border">
        <tr>
          <th><strong>项目名称</strong></th>
          <th><strong>文件名称</strong></th>
          <th><strong>地址</strong></th>
          <th><strong>日志日期</strong></th>
          <th style="width:15%;" class="text-center"><strong>操作</strong></th>
        </tr>
        </thead>
        <tbody class="no-border-y">
        <% @log_files.each_with_index do |f, index|%>
            <tr>
              <td><%= f.project_name %></td>
              <td><%= f.name %></td>
              <td><%= f.address %></td>
              <td><%= f.log_date %></td>
              <td class="text-center">
                <%= link_to content_tag(:i, '', class: "fa fa-flag"), edit_log_file_path(f), class: "label label-default" %>
                <%= link_to content_tag(:i, '', class: "fa fa-times"), log_file_path(f), class: "label label-danger", method: :delete, data: { confirm: "是否删除#{f.name}?" } %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/log_files/new.html.erb
<%= render 'shared/crumbs', menu: '系统管理', title: "日志获取", name: '初始化' %>
<%= render 'log_files/form' %>