config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  devise_for :users,controllers:{sessions:"users/sessions",confirmations:"users/confirmations",passwords:"users/passwords",registrations:"users/registrations" }, path: "auth",
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :home

  resources :users
  resources :roles
  resources :menus
  resources :log_files
  resources :sys_params
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  has_and_belongs_to_many :menus, :join_table => :roles_menus

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
  enum status: { active: 1, archived: 0 }
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  load_and_authorize_resource only: [:new, :edit, :index]

  def index
    @q = Role.ransack(params[:q])
  end

  def create
    role = Role.new(role_params)
    if role.save
      redirect_to :roles
    else
      render :new
    end
  end

  def update
    @role = Role.find(params[:id])
    if @role.update(role_params)
      redirect_to :roles
    else
      render :edit
    end
  end

  private

  def role_params
    params.require(:role).permit(:id, :name, :resource_type, :resource_id, :created_at, :updated_at, :menu_ids => [])
  end
end

app/views/roles/_form.html.erb
<%= bootstrap_form_for(@role, layout: :horizontal, :html => { class: 'pjax-form col-sm-10' }) do |f| %>
    <%= f.text_field :name, label: "角色名称" %>
    <%= f.collection_check_boxes :menu_ids, all_menus, :id, :name, label: "菜单", inline: true %>
    <div class="form-group text-center">
      <%= link_to '取消', roles_path, :class => 'btn btn-primary' %>
      <%= f.submit "保存", class: "btn btn-default" %>
    </div>
<% end %>

app/views/roles/edit.html.erb
<%= render 'shared/crumbs', menu: '系统管理', title: "角色信息", name: '编辑角色' %>
<%= render 'roles/form' %>

app/views/roles/index.html.erb
<%= render 'shared/crumbs', menu: '系统管理' ,title: "角色信息" %>


<div class="cl-mcont">
  <div class="head">
    <h3>查询</h3><hr/>
    <%= search_form_for @q, :html => {:class => 'pjax-form'} do |f| %>
        <div class="form-group col-md-4">
          <%= f.label "名称：", class: "control-label col-md-3" %>
          <div class="col-md-9">
            <%= f.search_field :name_cont, class: 'form-control' %>
          </div>
        </div>
        <%= link_to '新增', :new_role, class: "btn btn-info"%>
        <button type="submit" class="btn btn-success" data-toggle="modal" data-target="#search_model">查询</button>
    <% end %>
  </div>
</div>
<div class="cl-mcont">
  <div class="content">
    <div class="table-responsive">
      <table class="table no-border hover">
        <thead class="no-border">
        <tr>
          <th><strong>名称</strong></th>
          <th><strong>菜单</strong></th>
          <th style="width:15%;" class="text-center"><strong>操作</strong></th>
        </tr>
        </thead>
        <tbody class="no-border-y">
        <% @roles.each_with_index do |role, index| %>
          <tr>
            <td><%= role.name %></td>
            <td><%= role.menus.pluck(:name) %></td>
            <td class="text-center">
              <%= link_to  content_tag(:i, '', class: "fa fa-pencil"), edit_role_path(role), class: "label label-default" %>
              <a class="label label-danger" href="#"><i class="fa fa-times"></i></a>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/roles/new.html.erb
<%= render 'shared/crumbs', menu: '系统管理', title: "角色信息", name: '新建角色' %>
<%= render 'roles/form' %>