config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  devise_for :users,controllers:{sessions:"users/sessions",confirmations:"users/confirmations",passwords:"users/passwords",registrations:"users/registrations" }, path: "auth",
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :home

  resources :users
  resources :roles
  resources :menus
  resources :log_files
  resources :sys_params
end

app/models/sys_param.rb
class SysParam < ApplicationRecord
end

app/controllers/sys_params_controller.rb
class SysParamsController < ApplicationController
  load_and_authorize_resource except: [:create]
  def index
    @q = SysParam.ransack(params[:q])
  end

  def create
    @sys_param = SysParam.new(sys_param_params)
    if @sys_param.save
      flash[:notice] = "保存成功"
      redirect_to :sys_params
    else
      flash[:notice] = '保存失败'
      render :new
    end
  end

  def update
    if @sys_param.update(sys_param_params)
      flash[:notice] = '修改成功'
      redirect_to :sys_params
    else
      flash[:notice] = '修改失败'
      render :edit
    end
  end

  def destroy
    if @sys_param.destroy
      flash[:notice] = '删除成功'
    else
      flash[:notice] = '删除失败'
    end
    redirect_to :sys_params
  end

  private

  def sys_param_params
    params.require(:sys_param).permit(:name, :desc, :val, :code)
  end
end

app/helpers/sys_params_helper.rb
module SysParamsHelper
end

app/views/sys_params/_form.html.erb
<%= bootstrap_form_for(@sys_param, layout: :horizontal, :html => { class: 'pjax-form col-sm-10' }) do |f| %>
    <%= f.text_field :name, label: "参数名称" %>
    <%= f.text_field :code, label: '参数代码' %>
    <%= f.text_field :val, label: '参数值' %>
    <%= f.text_field :desc, label: '参数描述' %>
    <div class="form-group text-center">
      <%= link_to '取消', sys_params_path, :class => 'btn btn-primary' %>
      <%= f.submit "保存", class: "btn btn-default" %>
    </div>
<% end %>

app/views/sys_params/edit.html.erb
<%= render 'shared/crumbs', menu: '系统管理', title: "参数信息", name: '修改参数' %>
<%= render 'sys_params/form' %>

app/views/sys_params/index.html.erb
<%= render 'shared/crumbs', menu: '系统管理' ,title: "系统参数" %>


<div class="cl-mcont">
  <div class="head">
    <h3>查询</h3><hr/>
    <%= search_form_for @q, :html => {:class => 'pjax-form'} do |f| %>
        <div class="form-group col-md-4">
          <%= f.label "邮箱：", class: "control-label col-md-3" %>
          <div class="col-md-9">
            <%= f.search_field :name_cont, class: 'form-control' %>
          </div>
        </div>
        <%= link_to '新增', :new_sys_param, class: "btn btn-info"%>
        <button type="submit" class="btn btn-success" data-toggle="modal" data-target="#search_model">查询</button>
    <% end %>
  </div>
</div>
<div class="cl-mcont">
  <div class="content">
    <div class="table-responsive">
      <table class="table no-border hover">
        <thead class="no-border">
        <tr>
          <th><strong>名称</strong></th>
          <th><strong>值</strong></th>
          <th><strong>描述</strong></th>
          <th class="text-center"><strong>操作</strong></th>
        </tr>
        </thead>
        <tbody class="no-border-y">
        <% @sys_params.each_with_index do |p, index| %>
            <tr>
              <td><%= p.name %></td>
              <td><%= p.val %></td>
              <td><%= p.desc %></td>
              <td class="text-center">
                <%= link_to content_tag(:i, '', class: 'fa fa-pencil'), edit_sys_param_path(p), class: 'label label-default' %>
                <%= link_to content_tag(:i, '', class: "fa fa-times"), sys_param_path(p), class: "label label-danger", method: :delete, data: { confirm: "是否删除#{p.name}?" } %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/sys_params/new.html.erb
<%= render 'shared/crumbs', menu: '系统管理', title: "参数信息", name: '新建参数' %>
<%= render 'sys_params/form' %>